name: "Test self action"

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Deploy to laf
        uses: moonrailgun/laf-storage-deploy-action@master
        with:
          laf-server: "https://api.laf.dev"
          laf-pat: ${{ secrets.LAF_PAT }}
          laf-appid: ${{ secrets.LAF_APPID }}
          laf-bucket-name: ${{ secrets.LAF_BUCKET_NAME }}
          dist-path: "./test"
